#!/bin/bash
for PAIR in AUDJPY AUDUSD CADJPY EURCHF EURGBP EURJPY EURUSD GBPUSD NZDUSD USDCAD USDCHF USDJPY
# for PAIR in AUDJPY EURCHF EURGBP EURJPY GBPJPY
# for PAIR in AUDJPY CADJPY CHFJPY EURCHF EURGBP EURJPY GBPJPY
do
  qsub Transform.sh $PAIR
  echo $PAIR
done

